# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aa90317125bed437c9ea85b4526b96e80da04c39119457432c24ace041ffee8c42ce2d7cb91ae9a2fbfe630138a35a2c0f2563f027e0321c9f13f85ec522663


test:
  secret_key_base: 032600921488bde5c410dd2218f37daae9fe75fa4fe1af5c7d0d65bcb195c2b5690fd1642d861650506e93cad989c60f9b6dfa025138ef6adae182735e94ecbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
